# Prod
# db_url: mongodb://172.31.32.67:27017/

# Development
db_url: "mongodb://172.25.1.171:27017/"

APIKeyLength: "16"
APIChunkLength: "4"
UserIdLength: "4"

orgData:
  - orgId: "2928"
    orgName: "brillius"
    orgAddress: "Hyderabad"
    dbURI: ""

UsersData:
  - userid: "XXXX"
    firstname: "superadminfirst"
    lastname: "superadminlast"
    username: "superadmin"
    password: "a"
    email: "superadmin@gmail.com"
    number: "9876543210"
    role: "superadmin"
    tempOTP: ""
    tempOTPtimestamp: ""
    OTPattempts: ""
    OTPlocked: false
    OTPlockedtill: ""
  - userid: "GF8S"
    firstname: "adminfirst"
    lastname: "adminlast"
    username: "admin"
    password: "a"
    email: "admin@gmail.com"
    number: "9876543210"
    role: "admin"
    tempOTP: ""
    tempOTPtimestamp: ""
    OTPattempts: ""
    OTPlocked: false
    OTPlockedtill: ""
    organisation: "2928"
  - userid: "Z3QR"
    firstname: "userfirst"
    lastname: "userlast"
    username: "user"
    password: "a"
    email: "user@mail.com"
    number: "9876543210"
    role: "user"
    tempOTP: ""
    tempOTPtimestamp: ""
    OTPattempts: ""
    OTPlocked: false
    OTPlockedtill: ""
    organisation: "2928"

STTmodes:
  - mode: "Translate"
  - mode: "Transcribe"

STTmodelTypes:
  - modelType: "OpenAI"
  - modelType: "Distil"

STTmodelNames:
  - modelType: "OpenAI"
    modelName: "large-v2"
    engine: "openai/whisper-large-v2"
  - modelType: "OpenAI"
    modelName: "large"
    engine: "openai/whisper-large"
  - modelType: "OpenAI"
    modelName: "medium"
    engine: "openai/whisper-medium"
  - modelType: "OpenAI"
    modelName: "small"
    engine: "openai/whisper-small"
  - modelType: "OpenAI"
    modelName: "base"
    engine: "openai/whisper-base"
  - modelType: "OpenAI"
    modelName: "tiny"
    engine: "openai/whisper-tiny"
  - modelType: "Distil"
    modelName: "large-v2"
    engine: "distil-whisper/distil-large-v2"
  - modelType: "Distil"
    modelName: "medium-en"
    engine: "distil-whisper/distil-medium.en"

modeTypes:
  - type: "llm"
    modeType: "Private"
  - type: "llm"
    modeType: "Cloud"

LLMmodelTypes:
  - modelType: "llama2"
    modeType: "Private"
  - modelType: "mistral"
    modeType: "Private"
  - modelType: "vicuna"
    modeType: "Private"
  - modelType: "falcon"
    modeType: "Private"
  - modelType: "gpt2"
    modeType: "Private"
  - modelType: "Azure"
    modeType: "Cloud"
  - modelType: "OpenAI"
    modeType: "Cloud"

LLMmodelNames:
  - modelName: "TheBloke/Llama-2-7B-Chat-GGML"
    modelType: "llama2"
    engine: "llama-2-7b-chat.ggmlv3.q4_0.bin"
  - modelName: "TheBloke/Llama-2-13b-Chat-GGUF"
    modelType: "llama2"
    engine: "llama-2-13b-chat.Q4_K_M.gguf"
  - modelName: "TheBloke/Llama-2-7b-Chat-GGUF"
    modelType: "llama2"
    engine: "llama-2-7b-chat.Q4_K_M.gguf"
  - modelName: "TheBloke/Llama-2-70b-Chat-GGUF"
    modelType: "llama2"
    engine: "llama-2-70b-chat.Q4_K_M.gguf"
  - modelName: "NousResearch/Llama-2-7b-chat-hf"
    modelType: "llama2"
    engine: ""
  - modelName: "TheBloke/Llama-2-13B-chat-GPTQ"
    modelType: "llama2"
    engine: "model.safetensors"
  - modelName: "TheBloke/vicuna-13B-v1.5-GPTQ"
    modelType: "llama2"
    engine: "model.safetensors"
  - modelName: "TheBloke/Mistral-7B-OpenOrca-GPTQ"
    modelType: "mistral"
    engine: "model.safetensors"
  - modelName: "mistralai/Mistral-7B-v0.1"
    modelType: "mistral"
    engine: ""
  - modelName: "mistralai/Mistral-7B-Instruct-v0.1"
    modelType: "mistral"
    engine: ""
  - modelName: "TheBloke/Wizard-Vicuna-13B-Uncensored-GPTQ"
    modelType: "vicuna"
    engine: "Wizard-Vicuna-13B-Uncensored-GPTQ-4bit-128g.compat.no-act-order.safetensors"
  - modelName: "TheBloke/vicuna-7B-1.1-HF"
    modelType: "vicuna"
    engine: ""
  - modelName: "tiiuae/falcon-7b"
    modelType: "falcon"
    engine: ""
  - modelName: "tiiuae/falcon-40b"
    modelType: "falcon"
    engine: ""
  - modelName: "gpt2"
    modelType: "gpt2"
    engine: ""
  - modelName: "gpt2-xl"
    modelType: "gpt2"
    engine: ""
  - modelName: "Azure-Model-1"
    modelType: "Azure"
    engine: "gpt-3.5-turbo"
  - modelName: "Azure-Model-2"
    modelType: "Azure"
    engine: "gpt-4"
  - modelName: "GPT-3.5"
    modelType: "OpenAI"
    engine: "gpt-3.5-turbo-1106"
  - modelName: "GPT-4"
    modelType: "OpenAI"
    engine: "gpt-4"
  - modelName: "GPT-4 Turbo"
    modelType: "OpenAI"
    engine: "gpt-4-1106-preview"

RAGmodelNames:
  - modelName: "hkunlp/instructor-large"
  - modelName: "hkunlp/instructor-xl"
  - modelName: "intfloat/e5-large-v2"
  - modelName: "intfloat/e5-base-v2"
  - modelName: "all-MiniLM-L6-v2"
  - modelName: "intfloat/multilingual-e5-large"
  - modelName: "intfloat/multilingual-e5-base"

RAGdeviceTypes:
  - deviceType: "CPU"
  - deviceType: "GPU"
  - deviceType: "MPS"
